FROM python:3.9-slim-buster

ENV FLASK_APP=flask_app

WORKDIR /app

COPY requirements.txt requirements.txt
COPY requirements-test.txt requirements-test.txt

RUN apt-get -y update
RUN apt-get -y install python3-dev build-essential libssl-dev libffi-dev python3-setuptools
Run pip install --upgrade pip

RUN pip install -r requirements.txt -r requirements-test.txt

COPY . ./